name: ESP32 CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: esp-idf Toolchain Setup
      run: |
        sudo apt-get install gcc git wget make libncurses-dev flex bison gperf python python-serial
        wget https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
        tar zxvf xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
    - name: Build
      run: |
        export PATH=$(pwd)/xtensa-esp32-elf/bin:${PATH}
        export IDF_PATH=$(pwd)/esp-idf
        pip install -r ${IDF_PATH}/requirements.txt
        make
